<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jiaxin Su, Sumeng Xu, Ziqian Zhao">
<meta name="dcterms.date" content="2024-12-09">

<title>Vignette on bootstrapping and its application in predicting obesity levels; created as a class project for PSTAT197A in Fall 2024.</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Report_files/libs/clipboard/clipboard.min.js"></script>
<script src="Report_files/libs/quarto-html/quarto.js"></script>
<script src="Report_files/libs/quarto-html/popper.min.js"></script>
<script src="Report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Report_files/libs/quarto-html/anchor.min.js"></script>
<link href="Report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Report_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Report_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="Report_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="Report_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Vignette on bootstrapping and its application in predicting obesity levels; created as a class project for PSTAT197A in Fall 2024.</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jiaxin Su, Sumeng Xu, Ziqian Zhao </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading"></div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 9, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="basic-bootstrapping" class="level2">
<h2 class="anchored" data-anchor-id="basic-bootstrapping">Basic Bootstrapping</h2>
<p><strong>Bootstrap resampling/Bootstrapping</strong> is the process, pretending that our sample represents some notional population, and taking repeated samples of size N with replacement from our original sample of size N.</p>
<p>We use bootstrapping when we can’t take repeated samples from the same random process that generated our data, to see how our estimate changes from one sample to the next. The inability to resample is often due to factors such as the time-consuming nature of the process, the high cost of collecting additional data, and other practical constraints.</p>
</section>
<section id="process" class="level1">
<h1>Process</h1>
<ol type="1">
<li><p>Sampling N individuals from the population.</p></li>
<li><p>Create a bootstrapped dataset by sampling N observations with replacement from the original sample</p></li>
<li><p>Calculating some types of statistical metrics, like mean</p></li>
<li><p>Keeping track of the metrics for each bootstrap sample.</p></li>
<li><p>Repeating steps 2 to 4 a bunch of times</p>
<p><span style="color:red;">!!!</span> Make sure to keep each bootstrap sample must be of the same size (N) as the original sample.</p>
<p><span style="color:red;">!!!</span> Remember to have each bootstrap sample with replacement from the original sample.</p>
<p>Here is how bootstrapping looks like in a picture.</p></li>
</ol>
<p><img src="images/Screen%20Shot%202024-12-02%20at%2011.09.19%20PM.png" class="img-fluid"></p>
</section>
<section id="example" class="level1">
<h1>Example</h1>
<p>Imagine you want to estimate the average height of all adults in a city, but you only have a small sample of 100 individuals due to labor and money constraint. Calculating the sample mean gives you an estimate, but you’d also like to understand the variability of this estimate.</p>
<p>Using bootstrapping, you can simulate this process:</p>
<ol type="1">
<li><p>From your original sample of 100 individuals, randomly draw 100 data points with replacement. This means some individuals might appear multiple times in the new dataset, while others might not appear at all.</p></li>
<li><p>Calculate the mean height for this resampled dataset.</p></li>
<li><p>Repeat this resampling process many times (e.g., 10,000 iterations), creating a distribution of mean heights.</p></li>
</ol>
<p><span style="color:red;">!!!</span> This distribution of sample means (called the bootstrap distribution) allows you to estimate the standard error of the mean, construct confidence intervals, or test hypotheses about the population mean—all without requiring additional data collection.</p>
</section>
<section id="assumption" class="level1">
<h1>Assumption</h1>
<ol type="1">
<li><p>Bootstrapping assumes randomness in your data, and therefore the statistical uncertainty in your answer, arises from the process of sampling.</p></li>
<li><p>Bootstrapping is also a good approximation for other common forms of randomness as well, including experimental randomization, measurement error, and intrinsic variability of some natural process.</p></li>
</ol>
<p>In the following section we will demonstrate how to implement bootstrapping in R.</p>
</section>
<section id="basic-bootstrapping-1" class="level1">
<h1>Basic Bootstrapping</h1>
<p>First, let’s learn how to create bootstrap samples by randomly resampling the original data with replacement, enabling us to estimate variability in sample statistics such as the mean or standard error. We’ll use the <strong>Obesity_sample</strong> dataset as an example to demonstrate this process.</p>
<p>The dataset is from Kaggle <em>https://www.kaggle.com/datasets/fatemehmehrparvar/obesity-levels</em>, which is first introduced in the paper <em>Yağın, Fatma Hilal et al.&nbsp;“Estimation of Obesity Levels with a Trained Neural Network Approach optimized by the Bayesian Technique.” Applied Sciences (2023): n.&nbsp;pag.</em> to estimate obesity levels with neural network. The original data contains 17 attributes and 2111 observations. For our purpose in performing bootstrapping, we are going to randomly sample a smaller subset of the data set (700 observations) and perform a <strong>decision tree</strong> to do classification (in the later section).</p>
</section>
<section id="load-library-and-clean-dataset" class="level1">
<h1>Load library and clean dataset</h1>
<p>Let’s look at the dataset</p>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-2_fa4e5b1ee2b00e318834fb656f65de66">
<div class="cell-output-display">
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:200px; ">
<table class="table table-striped table-hover table-condensed table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: right; position: sticky; top: 0; background-color: #FFFFFF;">Age</th>
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;">Gender</th>
<th data-quarto-table-cell-role="th" style="text-align: right; position: sticky; top: 0; background-color: #FFFFFF;">Height</th>
<th data-quarto-table-cell-role="th" style="text-align: right; position: sticky; top: 0; background-color: #FFFFFF;">Weight</th>
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;">CALC</th>
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;">FAVC</th>
<th data-quarto-table-cell-role="th" style="text-align: right; position: sticky; top: 0; background-color: #FFFFFF;">FCVC</th>
<th data-quarto-table-cell-role="th" style="text-align: right; position: sticky; top: 0; background-color: #FFFFFF;">NCP</th>
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;">SCC</th>
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;">SMOKE</th>
<th data-quarto-table-cell-role="th" style="text-align: right; position: sticky; top: 0; background-color: #FFFFFF;">CH2O</th>
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;">family_history_with_overweight</th>
<th data-quarto-table-cell-role="th" style="text-align: right; position: sticky; top: 0; background-color: #FFFFFF;">FAF</th>
<th data-quarto-table-cell-role="th" style="text-align: right; position: sticky; top: 0; background-color: #FFFFFF;">TUE</th>
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;">CAEC</th>
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;">MTRANS</th>
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;">NObeyesdad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">22.00000</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">1.880000</td>
<td style="text-align: right;">90.00000</td>
<td style="text-align: left;">Sometimes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: right;">2.000000</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">no</td>
<td style="text-align: right;">1.000000</td>
<td style="text-align: left;">yes</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Always</td>
<td style="text-align: left;">Automobile</td>
<td style="text-align: left;">Overweight_Level_I</td>
</tr>
<tr class="even">
<td style="text-align: right;">29.00000</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">1.770000</td>
<td style="text-align: right;">83.00000</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: right;">1.000000</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">no</td>
<td style="text-align: right;">3.000000</td>
<td style="text-align: left;">no</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Frequently</td>
<td style="text-align: left;">Motorbike</td>
<td style="text-align: left;">Overweight_Level_I</td>
</tr>
<tr class="odd">
<td style="text-align: right;">20.00000</td>
<td style="text-align: left;">Female</td>
<td style="text-align: right;">1.630000</td>
<td style="text-align: right;">64.00000</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: right;">1.000000</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">no</td>
<td style="text-align: right;">2.000000</td>
<td style="text-align: left;">yes</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Always</td>
<td style="text-align: left;">Automobile</td>
<td style="text-align: left;">Normal_Weight</td>
</tr>
<tr class="even">
<td style="text-align: right;">20.00000</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">1.770000</td>
<td style="text-align: right;">70.00000</td>
<td style="text-align: left;">Sometimes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: right;">1.000000</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">no</td>
<td style="text-align: right;">2.000000</td>
<td style="text-align: left;">yes</td>
<td style="text-align: right;">1.000000</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Sometimes</td>
<td style="text-align: left;">Public_Transportation</td>
<td style="text-align: left;">Normal_Weight</td>
</tr>
<tr class="odd">
<td style="text-align: right;">22.82843</td>
<td style="text-align: left;">Male</td>
<td style="text-align: right;">1.710415</td>
<td style="text-align: right;">75.14286</td>
<td style="text-align: left;">Sometimes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: right;">2.786008</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">no</td>
<td style="text-align: right;">2.526193</td>
<td style="text-align: left;">yes</td>
<td style="text-align: right;">0.925118</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Sometimes</td>
<td style="text-align: left;">Public_Transportation</td>
<td style="text-align: left;">Overweight_Level_I</td>
</tr>
</tbody>
</table>
</div>

</div>
</div>
<section id="explore-the-sample-mean-of-weight-in-data-set" class="level2">
<h2 class="anchored" data-anchor-id="explore-the-sample-mean-of-weight-in-data-set">Explore the sample mean of weight in data set</h2>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-3_73595fd1aef652d74db53aed92884ac8">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>sample_weight <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Obesity_sample) <span class="sc">+</span> </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> Weight), <span class="at">binwidth=</span><span class="dv">5</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>sample_weight</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Report_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The histogram above displays the distribution of weights, with most data points concentrated between 40 and 100. It peaks around the 70-80 range, which is the most frequent weight in the data set.</p>
<p>To get a more precise data, we can use the following mean function to calculate the mean of sample weight.</p>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-4_615eb75b563b2c64bfa4b4a568c32dae">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>sample_weightm<span class="ot">&lt;-</span><span class="fu">mean</span>(<span class="sc">~</span>Weight, <span class="at">data=</span>Obesity_sample) </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(sample_weightm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 85.94483</code></pre>
</div>
</div>
<p>On average, the weight is around 85.94. However, since these samples are based on 700 observations, there is still variability when applying this result to the entire population in those countries.</p>
</section>
<section id="bootstrapping" class="level2">
<h2 class="anchored" data-anchor-id="bootstrapping">Bootstrapping</h2>
<p>Now, let’s practice doing <strong>a single bootstrap</strong></p>
<p>The first line of code creates a bootstrap sample from the original data (Obesity_sample) using the resample function from the mosaic package. As mentioned earlier, a bootstrap sample is generated by randomly selecting observations with replacement, meaning some rows may appear multiple times while others may not appear at all. This simulates taking a new sample from the same population.</p>
<p>The second line of code calculates the mean weight from the bootstrap sample.</p>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-5_875339d7ad1004ea370617f832281555">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1970</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>sample_weight_bootstrap <span class="ot">=</span> mosaic<span class="sc">::</span><span class="fu">resample</span>(Obesity_sample)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="sc">~</span>Weight, <span class="at">data=</span>sample_weight_bootstrap)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 86.79762</code></pre>
</div>
</div>
<p>The result is around 87, slightly higher than the sample mean. This difference represents a bootstrap sampling error, which occurs because the bootstrap sample may not perfectly represent the original data. However, a single bootstrap iteration provides only one estimate, which is not enough to understand the overall variability of the bootstrap process. To get a more comprehensive view, we need to perform multiple bootstrap iterations.</p>
<p>Let’s proceed to conduct <strong>1,000 bootstrap</strong> samples to better capture the distribution and variability of the bootstrap means.</p>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-6_1a650588f65b22a7589b05c5c7d9a3b8">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generating 10,000 bootstrap samples from Obesity_sample</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Then calculates the mean for each bootstrap sample</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1970</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>boot_weight <span class="ot">=</span> <span class="fu">do</span>(<span class="dv">10000</span>)<span class="sc">*</span><span class="fu">mean</span>(<span class="sc">~</span>Weight, <span class="at">data=</span>mosaic<span class="sc">::</span><span class="fu">resample</span>(Obesity_sample))</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(boot_weight) <span class="sc">+</span> </span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x=</span>mean))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Report_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This histogram shows the distribution of the means from 10,000 bootstrap samples. The graph is approximately symmetric and bell-shaped, centered around the original sample mean, which was close to 86.</p>
<p>Comparing this to the graph of the original sample mean, the bootstrap distribution helps us understand the uncertainty in the sample mean as an estimate of the population mean. The narrow spread in the bootstrap distribution suggests that the sample mean is a fairly precise estimate, as most bootstrap means are clustered close to the original sample mean.</p>
</section>
<section id="standard-errors" class="level2">
<h2 class="anchored" data-anchor-id="standard-errors">Standard Errors</h2>
<section id="bootstrapping-vs.-the-original-sample" class="level4">
<h4 class="anchored" data-anchor-id="bootstrapping-vs.-the-original-sample">Bootstrapping VS. the Original Sample</h4>
<p>First, let’s calculate the original sample’s standard error:</p>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-7_3a37a1fe83b950e4f643947e513e2ac8">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(Obesity_sample)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>std_err_weight <span class="ot">&lt;-</span> <span class="fu">sd</span>(<span class="sc">~</span>Weight, <span class="at">data =</span> Obesity_sample) <span class="sc">/</span> <span class="fu">sqrt</span>(n)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>std_err_weight</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.006241</code></pre>
</div>
</div>
<p>Then calculate the Bootstrap standard Error:</p>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-8_bd86a4f1479bc15ddf23d13612252a67">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>boot_std_error <span class="ot">&lt;-</span> boot_weight <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">std_err_weight =</span> <span class="fu">sd</span>(mean)) </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>boot_std_error</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  std_err_weight
1      0.9852292</code></pre>
</div>
</div>
<p>Although the two values are close (1.006 and 0.99), demonstrating consistency in the standard error estimate, there exists a difference of approximately 0.016, with the bootstrap standard error being slightly lower. This small discrepancy arises because the bootstrap method captures variability through resampling, which inherently smooths out extreme values by averaging across multiple simulated samples.</p>
<p>In contrast, the original sample standard error is derived solely from the observed dataset, assuming it is representative of the population and relying directly on the sample’s fixed variability. The lower bootstrap standard error suggests that the resampling approach estimates slightly less variability in the data compared to the original method, potentially reflecting a more refined measure of uncertainty.</p>
</section>
</section>
<section id="action-1" class="level2">
<h2 class="anchored" data-anchor-id="action-1">Action 1</h2>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-9_42192adcb22efefbaab1fcc9618387f0">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">confint</span>(boot_weight, <span class="at">level =</span> <span class="fl">0.95</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  name    lower   upper level     method estimate
1 mean 84.04354 87.8565  0.95 percentile 86.77514</code></pre>
</div>
</div>
<p>Above is the 95% confidence interval for the average weight.</p>
<p><strong>True or false</strong>: The histogram of the 1,000 Bootstrap, and the associated confidence interval, tell us that about 95% of all individuals weight between 84.04 and 87.86?</p>
<p>(answer: False: The histogram of the 1,000 Bootstrap and the associated confidence interval tell us that about 95% of the sample means (not individual weights) fall between 84.04 and 87.86. The confidence interval reflects the range within which we expect the true population mean to lie, based on the bootstrap sampling distribution of the mean, not the range of individual weights in the population.)</p>
</section>
<section id="action-2" class="level2">
<h2 class="anchored" data-anchor-id="action-2">Action 2</h2>
<p>Now, try to do the same bootstrapping process for weight based on Gender</p>
<hr>
<p>(answer below )</p>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-10_807f1c11c439696f47076ea31c05a204">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(Weight <span class="sc">~</span> Gender, <span class="at">data=</span>Obesity_sample)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Female     Male 
81.92943 89.75890 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">diffmean</span>(Weight <span class="sc">~</span> Gender, <span class="at">data=</span>Obesity_sample)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>diffmean 
7.829461 </code></pre>
</div>
</div>
<p>The difference in mean tells us that male weight 7.8 more than female.</p>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-11_ab4a5e56d938c09350804c4f3e2401d2">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1970</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># bootstrap </span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>boot_weight_gender <span class="ot">=</span> <span class="fu">do</span>(<span class="dv">10000</span>)<span class="sc">*</span><span class="fu">diffmean</span>(Weight <span class="sc">~</span> Gender, <span class="at">data=</span>mosaic<span class="sc">::</span><span class="fu">resample</span>(Obesity_sample))</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co">#visual </span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(boot_weight_gender) <span class="sc">+</span> </span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x=</span>diffmean))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Report_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 95% confidence interval</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(boot_weight_gender, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      name    lower    upper level     method estimate
1 diffmean 3.703572 11.68759  0.95 percentile 5.813157</code></pre>
</div>
</div>
<p>The bootstrap analysis estimates a difference in means of approximately 5.81, with a 95% confidence interval ranging from 3.7 to 11.69. The bootstrap estimate of 5.81 is slightly lower than the original observed difference of 7.83. This discrepancy reflects the inherent variability captured by the bootstrap method, which averages across multiple resampled datasets.</p>
<p>Additionally, the original difference of 7.83 lies well within the 95% confidence interval [3.70, 11.69], indicating that the observed difference is consistent with what could be expected under random sampling variability.</p>
</section>
<section id="basic-bootstrapping-conclusion" class="level2">
<h2 class="anchored" data-anchor-id="basic-bootstrapping-conclusion">Basic Bootstrapping Conclusion:</h2>
<p>Now, hope you already learned the basic of doing bootstrap! So far, we explored the concept and application of bootstrapping, a resampling method used to estimate the variability and confidence intervals of sample statistics.</p>
<hr>
</section>
</section>
<section id="application" class="level1">
<h1>Application</h1>
<p>After we have an idea about what bootstrap is, let’s go over a simple example to see its application in a classification prediction task and its impact.</p>
<p>In this example, we aim to do two decision trees with original data set and bootstrapped data set, and investigate the changes in accuracy and the impact on prediction.</p>
</section>
<section id="decision-tree-without-bootstrapping" class="level1">
<h1>Decision Tree Without Bootstrapping</h1>
<section id="partition-training-and-testing" class="level2">
<h2 class="anchored" data-anchor-id="partition-training-and-testing">Partition training and testing</h2>
<p>We parition the data into 80% training and 20% testing stratified by the response <code>NObeyesdad</code>. We’ll also use 5 folds to perform stratifies cross validation.</p>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-12_9999e3112963a0e4f9469048d0f653a4">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>partitions <span class="ot">&lt;-</span> Obesity_sample <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">initial_split</span>(<span class="at">prop =</span> <span class="fl">0.8</span>, <span class="at">strata =</span> NObeyesdad)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>Obesity_train <span class="ot">&lt;-</span> <span class="fu">training</span>(partitions)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>Obesity_test <span class="ot">&lt;-</span> <span class="fu">testing</span>(partitions)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>Obesity_folds <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(Obesity_train , <span class="at">v =</span> <span class="dv">5</span>, <span class="at">strata =</span> NObeyesdad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-visualization" class="level2">
<h2 class="anchored" data-anchor-id="data-visualization">Data Visualization</h2>
<p>Firstly, we see the distribution of our response variable in training data set:</p>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-13_40ecf5b04c01139acb2d69610641d5b3">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Report_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Obesity Status without Bootstrap</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="recipe" class="level2">
<h2 class="anchored" data-anchor-id="recipe">Recipe</h2>
<p>We are going to use all predictors to predict obesity status <code>NObeyesdad</code>.</p>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-14_e523a423d13a431e112c21f28a82ff96">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating Recipe using all variables</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>Obesity_recipe <span class="ot">&lt;-</span><span class="fu">recipe</span>(NObeyesdad <span class="sc">~</span> ., <span class="at">data =</span> Obesity_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="creating-decision-tree-model" class="level2">
<h2 class="anchored" data-anchor-id="creating-decision-tree-model">Creating Decision Tree Model</h2>
<p>We create a decision tree tuning the hyperparameter <code>cost_complexity</code></p>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-15_59dd798fa7e8d954b242a12a35410e4f">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tuning cost_complexity</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>Obesity_tree <span class="ot">&lt;-</span> <span class="fu">decision_tree</span>(<span class="at">cost_complexity =</span> <span class="fu">tune</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"rpart"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"classification"</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating Decision Tree Workflow</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>Obesity_workflow <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(Obesity_tree) <span class="sc">%&gt;%</span> </span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(Obesity_recipe)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>param_grid <span class="ot">&lt;-</span> <span class="fu">grid_regular</span>(<span class="fu">cost_complexity</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">4.5</span>, <span class="sc">-</span><span class="dv">2</span>)), <span class="at">levels =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-16_2389f496fa2a7f9397b31584feb4e002">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tune the model</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>Obesity_tune_tree <span class="ot">&lt;-</span> <span class="fu">tune_grid</span>(</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  Obesity_workflow,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">resamples =</span> Obesity_folds,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">grid =</span> param_grid,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics =</span> <span class="fu">metric_set</span>(roc_auc)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="co"># save(Obesity_tune_tree, file = "../results/Obesity_tune_tree.RData")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="visualize-result-of-original-data" class="level2">
<h2 class="anchored" data-anchor-id="visualize-result-of-original-data">Visualize Result of Original data</h2>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-17_1abff2ac2266d9ff622bfae5c01de130">
<div class="cell-output-display">
<p><img src="Report_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="decision-tree-with-bootstrapping" class="level1">
<h1>Decision Tree with bootstrapping</h1>
<section id="bootstrapping-1" class="level2">
<h2 class="anchored" data-anchor-id="bootstrapping-1">Bootstrapping</h2>
<p>We bootstrap the training set for 1000 times.</p>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-19_d805848ce84ff6dbfe62a0ba87d99b78">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2345</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>boot_Obesity <span class="ot">&lt;-</span> mosaic<span class="sc">::</span><span class="fu">resample</span>(Obesity_train,<span class="at">times =</span> <span class="dv">1000</span>,<span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>boot_Obesity <span class="ot">&lt;-</span> boot_Obesity <span class="sc">%&gt;%</span> </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>orig.id)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="visualize-response-variable" class="level2">
<h2 class="anchored" data-anchor-id="visualize-response-variable">Visualize Response Variable</h2>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-20_521ae9a14f8871477b04408214dc0343">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Report_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Obesity Status with Bootstrap</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="compare-with-before-bootstrapping" class="level2">
<h2 class="anchored" data-anchor-id="compare-with-before-bootstrapping">Compare with before bootstrapping</h2>
<p>Here we visualize the distribution of our response variables from two training set.</p>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-21_070b8e9b5793f93b92367a0f6a5f26c3">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Report_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Comparison of Obesity Status across training set</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="new-recipe-and-model" class="level2">
<h2 class="anchored" data-anchor-id="new-recipe-and-model">New Recipe and Model</h2>
<p>We use the same recipe with data changed to bootstrapped data. Perform the exact same procedure as before to see the impact of bootstrapping.</p>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-22_2f12c6e4935fbe6efc3ae4d3cd3aaa7e">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Recipe</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>Obesity_recipe_bt <span class="ot">&lt;-</span><span class="fu">recipe</span>(NObeyesdad <span class="sc">~</span> ., <span class="at">data =</span> boot_Obesity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-23_0ed4c8381864801d851d7d682470a378">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Workflow</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>Obesity_workflow_bt <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(Obesity_tree) <span class="sc">%&gt;%</span> </span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(Obesity_recipe_bt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-24_fac86241e17cb3a5008d79d65c975874">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tune model</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>Obesity_tune_tree_bt <span class="ot">&lt;-</span> <span class="fu">tune_grid</span>(</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  Obesity_workflow_bt,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">resamples =</span> Obesity_folds,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">grid =</span> param_grid,</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics =</span> <span class="fu">metric_set</span>(roc_auc)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="co"># save(Obesity_tune_tree_bt, file = "../results/Obesity_tune_tree_bt.RData")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="visualize-result-with-bootstrapped-data" class="level2">
<h2 class="anchored" data-anchor-id="visualize-result-with-bootstrapped-data">Visualize Result with Bootstrapped data</h2>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-25_fa97dd349a84ef918615ccfaa78203f2">
<div class="cell-output-display">
<p><img src="Report_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<table class="table">
<thead>
<tr class="header">
<th>Model</th>
<th>Cost_Complexity</th>
<th>ROC_AUC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Without Bootstrap</td>
<td>3.162278e-05</td>
<td>0.9548125</td>
</tr>
<tr class="even">
<td>With Bootstrap</td>
<td>3.162278e-05</td>
<td>0.9548125</td>
</tr>
</tbody>
</table>
<p>Here, as we expected the performance, the performance is similar. Actually, in our case, the metric for these two model is exactly the same, which possibly attribute to the very similar training set we have. Additionally, we are using a <strong>decision tree</strong> purely for learning purpose, which, a simple model, might be less sensitive to the change in data set.</p>
</section>
</section>
<section id="result" class="level1">
<h1>Result</h1>
<p>We then fit our model with the best <strong>cost_complexity</strong> and predict on our test set.</p>
<section id="prediction-with-two-models" class="level2">
<h2 class="anchored" data-anchor-id="prediction-with-two-models">Prediction with two models</h2>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-28_a221aad5550fe96b8ac473797d59172c">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>best_complexity <span class="ot">&lt;-</span> <span class="fu">select_best</span>(Obesity_tune_tree)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>Ori_Obesity_tree_final <span class="ot">&lt;-</span> <span class="fu">finalize_workflow</span>(Obesity_workflow, best_complexity)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>Ori_Obesity_model <span class="ot">&lt;-</span> <span class="fu">fit</span>(Ori_Obesity_tree_final, <span class="at">data =</span> Obesity_train)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>Ori_Obesity_model_test <span class="ot">&lt;-</span> <span class="fu">augment</span>(Ori_Obesity_model, </span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>                               Obesity_test) <span class="sc">%&gt;%</span> </span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(NObeyesdad, <span class="fu">starts_with</span>(<span class="st">".pred"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-29_0984d7fde21f883206903ec212b0f43e">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>best_complexity_bt <span class="ot">&lt;-</span> <span class="fu">select_best</span>(Obesity_tune_tree_bt)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>bt_Obesity_tree_final <span class="ot">&lt;-</span> <span class="fu">finalize_workflow</span>(Obesity_workflow, best_complexity_bt)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>bt_Obesity_model <span class="ot">&lt;-</span> <span class="fu">fit</span>(bt_Obesity_tree_final, <span class="at">data =</span> boot_Obesity)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>bt_Obesity_model_test <span class="ot">&lt;-</span> <span class="fu">augment</span>(bt_Obesity_model, </span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>                               Obesity_test) <span class="sc">%&gt;%</span> </span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(NObeyesdad, <span class="fu">starts_with</span>(<span class="st">".pred"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="visualize-the-roc-curve-for-both-prediction-model" class="level2">
<h2 class="anchored" data-anchor-id="visualize-the-roc-curve-for-both-prediction-model">Visualize the ROC curve for both prediction model</h2>
<div class="cell" data-hash="Report_cache/html/unnamed-chunk-30_6b975be0bd4a7598a5659d47ed502d49">
<div class="cell-output-display">
<p><img src="Report_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the <strong>roc curve</strong>, we could see that models trained by bootstrapped data hugs the top-left corner more than the model without bootstrapping.</p>
<table class="table">
<thead>
<tr class="header">
<th>Model</th>
<th>Accuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Without Bootstrap</td>
<td>0.845</td>
</tr>
<tr class="even">
<td>With Bootstrap</td>
<td>0.859</td>
</tr>
</tbody>
</table>
<p>Here, we can see that after bootstrapping, the accuracy does improved a little, which aligns our expectation.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>Bootstrapping is a powerful statistical tool with several advantages however, it also has some drawbacks such as computational expenses. Here are some pros and cons of bootstrapping:</p>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Pros</th>
<th>Cons</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No assumptions about the underlying population distribution</td>
<td>Computational intensive by requiring large of resamples</td>
</tr>
<tr class="even">
<td>Interpretable by its relatively simple computation method</td>
<td>Sensitive to outliers</td>
</tr>
</tbody>
</table>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>